namespace InternationalShopper.Bot;

public enum Env
{
    TELEGRAM_TOKEN,
    TELEGRAM_WEBHOOK_SECRET,
    REDDIT_USER_NAME,
    DATABASE_HOST,
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_NAME,
    ASPNETCORE_URLS,
    REDDIT_SERVICE_DELAY_IN_MINUTES
}