// <auto-generated />
using InternationalShopper.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternationalShopper.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210143255_Add-EntityType-Column-Into-Keywords-Table")]
    partial class AddEntityTypeColumnIntoKeywordsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternationalShopper.Database.Models.BotSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LastProcessedMessageUTC")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.Keyword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrackedCountryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrackedCountryId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.TelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.TrackedCountry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("TrackedCountries");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.Keyword", b =>
                {
                    b.HasOne("InternationalShopper.Database.Models.TrackedCountry", "TrackedCountry")
                        .WithMany("Keywords")
                        .HasForeignKey("TrackedCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedCountry");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.TrackedCountry", b =>
                {
                    b.HasOne("InternationalShopper.Database.Models.TelegramUser", "TelegramUser")
                        .WithMany("TrackedCountries")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.TelegramUser", b =>
                {
                    b.Navigation("TrackedCountries");
                });

            modelBuilder.Entity("InternationalShopper.Database.Models.TrackedCountry", b =>
                {
                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
